version: 0.0
os: linux
files:
  - source: /docs
    destination: /var/www/html/
  - source: /includes
    destination: /var/www/html/
  - source: /db.php
    destination: /var/www/html/
  - source: /delete_task.php
    destination: /var/www/html/
  - source: /edit.php
    destination: /var/www/html/
  - source: /index.php
    destination: /var/www/html/
  - source: /save_task.php
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: Scripts/install_dependencies.txt
      timeout: 300
      runas: root
    - location: Scripts/start_server.txt
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Scripts/stop_server.txt
      timeout: 300
      runas: root